In [9]:
s = "Esta es la secuencia"
l = []
for i in s:
    l.append(i)
l.reverse()
print(l)


['a', 'i', 'c', 'n', 'e', 'u', 'c', 'e', 's', ' ', 'a', 'l', ' ', 's', 'e', ' ', 'a', 't', 's', 'E']


In [ ]:
s1 = "hola caracola"
s2 = "adios marieta"
l = []

for i in range(len(s1)):
    l.append(s1[i])
    l.append(s2[i])
      
print(l)

['h', 'a', 'o', 'd', 'l', 'i', 'a', 'o', ' ', 's', 'c', ' ', 'a', 'm', 'r', 'a', 'a', 'r', 'c', 'i', 'o', 'e', 'l', 't', 'a', 'a']


In [27]:
s1 = "murcielago"
l = []
s1.lower()
for i in s1:
    if i != "a" and i != "e" and i != "i" and i != "o" and i != "u":
        l.append(i)

print(l)   


['m', 'r', 'c', 'l', 'g']


In [62]:
s = "zorra arro1"
l = []
l_inv = []

for i in range(len(s)):
    l.append(s[i])
    l_inv.append(s[len(s)-1-i])

if l == l_inv:
    print("Es un palindromo")
else:
    print("No es un palindromo")


No es un palindromo


In [71]:
m = [[1,2,3],[4,5,6],[7,8,9]]
max = [0,0,0]
for i in range(3):
    for j in range(3):
        if max[i] < m[i][j]:
            max[i] = m[i][j]  
        else:
            max[i]
print(max)

[3, 6, 9]


In [74]:
import numpy as np
n = int(input("Inserta n: "))
A = np.zeros((n,n))
val = 0
for i in range(n):
    for j in range(n):
        A[i][j] = val
        val+=1
print(A)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [ ]:
import numpy as np
n = int(input("Inserta n: "))
m = int(input("Inserta n: "))
A = np.zeros((n,m))

for i in range(n):
    for j in range(m):
        A[i][j] = int(input("valor"))

col_sum = np.zeros(m)
print(col_sum)
for i in range(m):
    for j in range(n):
        col_sum[i] += A[j][i]

print(col_sum)


        



[0. 0.]
[4. 6.]


In [168]:
import numpy as np
n = int(input("Inserta dimension: "))
A = np.zeros((n,n))

for i in range(n):
    for j in range(n):
        A[i][j] = int(input("valor"))

B = np.eye((n))

print("Es la matriz identidad") if np.array_equal(A, B) else print("No es la matriz identidad")

Es la matriz identidad


In [ ]:
import numpy as np
n = int(input("Inserta filas: "))
m = int(input("Inserta Columnas: "))
A = np.zeros((n,m))

for i in range(n):
    for j in range(m):
        A[i][j] = int(input("valor"))

A_T = A.T

print(A)
print('')
print(A_T)


[[1. 2. 3.]
 [4. 5. 6.]]

[[1. 4.]
 [2. 5.]
 [3. 6.]]


In [ ]:
import numpy as np
n = int(input("Inserta dimension: "))
A = np.eye((n))

print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
shopping_list = []
shopping_list = ["Botella ron"]*30
shopping_list.extend(["Hamburguesas"]*6)
shopping_list.extend(["Tomates"]*3)
shopping_list.extend(["Queso","ketchup","Mostaza"])

print(shopping_list)

counted = []
for item in shopping_list:
    if item not in counted:
        counted.append(item)
        print("{} de {}".format(shopping_list.count(item), item))


['Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Botella ron', 'Hamburguesas', 'Hamburguesas', 'Hamburguesas', 'Hamburguesas', 'Hamburguesas', 'Hamburguesas', 'Tomates', 'Tomates', 'Tomates', 'Queso', 'ketchup', 'Mostaza']
30 de Botella ron
6 de Hamburguesas
3 de Tomates
1 de Queso
1 de ketchup
1 de Mostaza
